# Configuration for Acme Company
company_name: "Acme AI"
default_language: "he"
persona_prompt_he: "אתה נציג שירות לקוחות אדיב ומקצועי מטעם Acme AI. ענה בקצרה ובנימוס."
qdrant_index_name: "acme_docs"
callback_sheet_id: "GOOGLE_SHEET_ID_HERE"
